#!/bin/bash

./node_modules/.bin/webpack --config webpack.production.js --optimize-minimize

# this is so that
# ./gems/canvas_i18nliner/bin/i18nliner generate_js
# doesn't shit the bed
mkdir -p dist/canvas_spaces
